services:
  mariadb-shard0:
    image: mariadb:10.11
    container_name: mariadb-shard0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shard0
    ports:
      - "3310:3306"
    volumes:
      - shard0-data:/var/lib/mysql
      - ./init-shard0.sql:/docker-entrypoint-initdb.d/init.sql

  mariadb-shard1:
    image: mariadb:10.11
    container_name: mariadb-shard1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shard1
    ports:
      - "3311:3306"
    volumes:
      - shard1-data:/var/lib/mysql
      - ./init-shard1.sql:/docker-entrypoint-initdb.d/init.sql

  mariadb-shard2:
    image: mariadb:10.11
    container_name: mariadb-shard2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shard2
    ports:
      - "3312:3306"
    volumes:
      - shard2-data:/var/lib/mysql
      - ./init-shard2.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  shard0-data:
  shard1-data:
  shard2-data: